### PR TITLE
Fixed for Symfony 3.x

### PR DESCRIPTION
**Pull request by Dray2na**
Added 'read_only' default flag to 'MultipleFileUploadType' class, to avoid "The option 'read_only' does not exist" error in sonata 3.x

### CODE REVIEW

**Comment by christian-kolb** [comment]
Thanks for the update. Few comments:

- Pull request title does not work because Sonata is already on 3.*. It's symfony you're updating it for, aren't you?
- The Nelmio bundle shouldn't be in there at all (my bad). Can you remove the Nelmio comments in the doc block sections and remove the use statement all together?

**Comment by christian-kolb** [comment]
Perfect, thanks.

**Comment by Dray2na** [comment]
Hey there, thanks for your feedback and for the merge! I hope it all fits so.

**Comment by christian-kolb** [comment]
Looks very good, thanks for the pull request ; )

**Pull request merged**
